services:
  web:
    build:
      context: ../../
      dockerfile: config/docker/Dockerfile
      target: development
    container_name: ${COMPOSE_PROJECT_NAME:-workspace}-web
    ports:
      - "${DOCKER_HOST_PORT:-8000}:${DOCKER_CONTAINER_PORT:-8000}"
    volumes:
      - type: bind
        source: ../../
        target: /workspace
      - type: volume
        source: node_modules
        target: /workspace/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG_MODE:-false}
      - PORT=${DOCKER_CONTAINER_PORT:-8000}
    working_dir: /workspace
    command: python src/main.py
    restart: unless-stopped
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME:-workspace}-network

volumes:
  node_modules:
    name: ${COMPOSE_PROJECT_NAME:-workspace}-node_modules
