name: "系统维护工作流"
description: "定期系统维护和优化"

schedule: "0 2 * * 0"  # 每周日凌晨2点

stages:
  - name: "系统清理"
    steps:
      - name: "清理日志文件"
        command: "find /var/log -name '*.log' -mtime +30 -delete"
      - name: "清理临时文件"
        command: "find /tmp -type f -mtime +7 -delete"
      - name: "Docker清理"
        command: "docker system prune -f"
        
  - name: "备份"
    steps:
      - name: "配置备份"
        command: "./config/backup/backup_strategy.sh config_backup"
      - name: "数据备份"
        command: "./config/backup/backup_strategy.sh data_backup"
        
  - name: "系统优化"
    steps:
      - name: "性能优化"
        command: "./config/optimization/continuous_optimizer.sh"
      - name: "安全更新"
        command: "./config/security/security_hardening.sh update"
        
  - name: "健康检查"
    steps:
      - name: "系统状态检查"
        command: "./config/monitoring/alerting.sh health_check"
      - name: "生成报告"
        command: "./config/docs/documentation_manager.sh --generate-report"
